package com.bank.agent.controller;

import com.bank.agent.model.AgentRequest;
import com.bank.agent.model.AgentResponse;
import com.bank.agent.service.AgentService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * REST entry point for the AI Agent.
 *
 * POST /api/agent/query          — submit a natural-language prompt
 * GET  /api/agent/health         — liveness check
 * GET  /api/agent/download/{fn}  — download a generated PDF report
 */
@RestController
@RequestMapping("/api/agent")
public class AgentController {

    private static final Logger log = LoggerFactory.getLogger(AgentController.class);

    private final AgentService agentService;

    public AgentController(AgentService agentService) {
        this.agentService = agentService;
    }

    @PostMapping("/query")
    public ResponseEntity<AgentResponse> query(@RequestBody AgentRequest request) {
        if (request.prompt() == null || request.prompt().isBlank()) {
            return ResponseEntity.badRequest()
                    .body(new AgentResponse("Prompt must not be empty."));
        }

        log.info("Received agent query: {}", request.prompt());
        String answer = agentService.processQuery(request.prompt());
        return ResponseEntity.ok(new AgentResponse(answer));
    }

    /** Simple health-check endpoint for demo use. */
    @GetMapping("/health")
    public ResponseEntity<String> health() {
        return ResponseEntity.ok("AI Agent is running — Tools: ReportTool, MailTool, UserFetchTool, LoanReportPdfTool");
    }

    /**
     * Serves a PDF report file generated by LoanReportPdfTool.
     * Files are stored in the system temp directory under /bank-reports/.
     * Only filenames ending in .pdf are served to prevent directory traversal.
     */
    @GetMapping("/download/{filename:.+}")
    public ResponseEntity<Resource> download(@PathVariable String filename) {
        // Safety: reject any filename that tries to escape the reports directory
        if (!filename.endsWith(".pdf") || filename.contains("..") || filename.contains("/") || filename.contains("\\")) {
            return ResponseEntity.badRequest().build();
        }

        Path filePath = Paths.get(System.getProperty("java.io.tmpdir"), "bank-reports", filename);

        if (!Files.exists(filePath)) {
            log.warn("Requested PDF not found: {}", filePath);
            return ResponseEntity.notFound().build();
        }

        Resource resource = new FileSystemResource(filePath);
        log.info("Serving PDF download: {}", filename);

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"")
                .contentType(MediaType.APPLICATION_PDF)
                .body(resource);
    }
}
