-- ─────────────────────────────────────────────────────────────────────────────
-- H2 Schema for AI Agent Demo
-- All data is fictional; loaded fresh on every application start.
-- ─────────────────────────────────────────────────────────────────────────────

DROP TABLE IF EXISTS LOANS;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS ACCOUNTS;

CREATE TABLE ACCOUNTS (
    ACCOUNT_NUMBER  VARCHAR(20)     NOT NULL PRIMARY KEY,
    CUSTOMER_NAME   VARCHAR(100)    NOT NULL,
    ACCOUNT_TYPE    VARCHAR(20)     NOT NULL, -- SAVINGS | CURRENT | FIXED_DEPOSIT
    BALANCE         DECIMAL(15, 2)  NOT NULL DEFAULT 0.00,
    DEPARTMENT      VARCHAR(50),
    OPENED_DATE     DATE            NOT NULL
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID   BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER   VARCHAR(20)     NOT NULL REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
    TRANSACTION_DATE DATE            NOT NULL,
    AMOUNT           DECIMAL(15, 2)  NOT NULL,
    TRANSACTION_TYPE VARCHAR(20)     NOT NULL, -- CREDIT | DEBIT | TRANSFER
    DEPARTMENT       VARCHAR(50),
    DESCRIPTION      VARCHAR(255)
);

CREATE TABLE LOANS (
    LOAN_ID             BIGINT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCOUNT_NUMBER      VARCHAR(20)     NOT NULL REFERENCES ACCOUNTS(ACCOUNT_NUMBER),
    LOAN_TYPE           VARCHAR(30)     NOT NULL, -- HOME | AUTO | PERSONAL | EDUCATION
    PRINCIPAL_AMOUNT    DECIMAL(15, 2)  NOT NULL,
    OUTSTANDING_AMOUNT  DECIMAL(15, 2)  NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL, -- ACTIVE | CLOSED | DEFAULTED
    DEPARTMENT          VARCHAR(50)
);
